apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: example
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiImplementation: Intel
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: ghcr.io/blazej-smorawski/example-sycl-mpi:latest
            imagePullPolicy: Always
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
              runAsGroup: 109
            args:
            - mpirun
            - -genv 
            - I_MPI_DEBUG=2
            - -n
            - "2"
            #- ls
            - /home/mpiuser/example
            - "2000"
            - "2000"
            - "2000"
            resources:
              limits:
                cpu: 1
                memory: 4Gi
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: ghcr.io/blazej-smorawski/example-sycl-mpi:latest
            imagePullPolicy: Always
            name: mpi-worker
            securityContext:
              runAsUser: 1000
              runAsGroup: 109
            command:
            args:
            - /usr/sbin/sshd
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              limits:
                cpu: 1
                memory: 4Gi
                gpu.intel.com/i915: 1
